### ISSUE TITLE
Error PA8 required by ETB enable but used by ETB disable?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/hellen154hyundai#102]
<img width="533" alt="image" src="https://github.com/rusefi/hellen154hyundai/assets/5685108/73fc3fd0-3b41-4c6a-8608-70aec0ecf395">

**Comment by rusefillc** [comment]
@ElDominio what board rev? Please link tune

**Comment by Ankyth** [comment]
[CurrentTune - Copy.zip](https://github.com/rusefi/hellen154hyundai/files/11537021/CurrentTune.-.Copy.zip)

REV. B

**Comment by rusefillc** [comment]
@Ankyth please try again in 29 minutes from now or later

looks like rev C tune loaded into rev B? anyway in 28 minutes this should work better

**Comment by Ankyth** [comment]
Updated firmware and its fixed

**Comment by Ankyth** [comment]
Started the car again, had to update again and with the key on, the throttle dances from 0 to 100 over and over, once i turn the car it goes 100% open, even after calibrating

**Comment by rusefillc** [comment]
@Ankyth looks like a separate issue need separate ticket with tune and log

**Comment by ElDominio** [comment]
Problem fixed by activating stepper mode and switching h bridge direction
