### ISSUE TITLE
Throttle goes to 100% when starting car

### ISSUE THREAD

**Issue by Ankyth** [rusefi/hellen154hyundai#103]
[throttle not calibrating revC.zip](https://github.com/rusefi/hellen154hyundai/files/11560261/throttle.not.calibrating.revC.zip)

[CurrentTune.zip](https://github.com/rusefi/hellen154hyundai/files/11560267/CurrentTune.zip)

**Comment by Ankyth** [comment]
![image](https://github.com/rusefi/hellen154hyundai/assets/124215929/ad93050e-aea9-44ee-95b2-fb972332f90a)

Throttle wide open while ecu reads 5.7%

**Comment by Ankyth** [comment]
@rusefillc

**Comment by rusefillc** [comment]
@Ankyth I have a feeling that we are dealing with something weird from C tune loaded into B

like for instance here is the potential issue

![image](https://github.com/rusefi/hellen154hyundai/assets/48498823/665e067c-2e79-4b99-8102-73b633d571f2)

**Comment by rusefillc** [comment]
@Ankyth please try with latest firmware in 24 minutes from now - firmware would be auto-adjusting "inverted driver pins" flag based on board revision

**Comment by Ankyth** [comment]
Tested and it did not work properly, after calibrating, gauges show like this
![image](https://github.com/rusefi/hellen154hyundai/assets/124215929/bfd2c767-bab9-41c5-be15-67f45308c7da)

Throttle IS closed fully but it works backwards, i can turn the car on, you press the pedal and does nothing, you release the pedal and it accelerates the amount you pressed the pedal

[CurrentTune (5-27).zip](https://github.com/rusefi/hellen154hyundai/files/11582515/CurrentTune.5-27.zip)

**Comment by rusefillc** [comment]
@Ankyth please reset tune and test default

**Comment by Ankyth** [comment]
> @Ankyth I have a feeling that we are dealing with something weird from C tune loaded into B
> 
> like for instance here is the potential issue
> 
> ![image](https://user-images.githubusercontent.com/48498823/241075459-665e067c-2e79-4b99-8102-73b633d571f2.png)

Where is this option?

**Comment by rusefillc** [comment]
@Ankyth reminder about top-right corner "Search" button in TS

i really suggest "reset firmware"

**Comment by Ankyth** [comment]
Issue fixed, car working as normal
