### ISSUE TITLE
Why is there a 12pin connector with only 5 pins in use?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/hellen154hyundai#106]
Is there no i/o left for more?

Haltech has
2x analog
2x digital
4x output

on their connector, do we only have enough for the current setup? or are there undocumented pins?

**Comment by ElDominio** [comment]
<img width="949" alt="image" src="https://github.com/rusefi/hellen154hyundai/assets/5685108/fe3906d6-c70e-47df-b0f8-1c078f7063e5">

I see it was changed in firmware, but there is no user facing mention of this; where are they on the connector?

**Comment by rusefillc** [comment]
@ElDominio remember how snapshot takes some time to build? Same thing with pinout - it takes some time to build once file is updated.

https://rusefi.com/docs/pinouts/hellen/hellen154hyundai/?pin=X11

one pin is a separate issue https://github.com/rusefi/hellen154hyundai/issues/107
