### ISSUE TITLE
AIN3 uses IN_VSS which does not seem to be analog capable

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#107]
![image](https://github.com/rusefi/hellen154hyundai/assets/48498823/3d4e2bcd-841c-48a3-b48c-28f5a41b347f)

![image](https://github.com/rusefi/hellen154hyundai/assets/48498823/6c61dad3-8a09-42f6-8c2b-13a2463ff937)

**Comment by ElDominio** [comment]
Is it digital or analog?

**Comment by Qwerty-OFF** [comment]
Fixed
