### ISSUE TITLE
re-fab rev C

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#110]
Need alternative part for F6、F5、F4、F3 please?

**Comment by Qwerty-OFF** [comment]
C529795

**Comment by rusefillc** [comment]
@Qwerty-OFF https://github.com/rusefi/hellen154hyundai/commit/84da73a741f710f84cbcec39418a896e41557b97 проверь пожалуйста

**Comment by Qwerty-OFF** [comment]
@rusefillc выглядит хорошо
