### ISSUE TITLE
Smiley face "Daniel" board now "3.6-1"

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#112]
Some traces are FUBAR we would have to try the other fix on this board?

![WhatsApp Image 2023-06-30 at 14 53 03](https://github.com/rusefi/hellen154hyundai/assets/48498823/070a1353-a40a-4393-a039-e246d0ba4ddf)

**Comment by Qwerty-OFF** [comment]
Install R72 4.7k

**Comment by rusefillc** [comment]
Installed R72 4.7k
added two 0R

all three lines measure 4.7K

**Comment by rusefillc** [comment]
Ray says it works!
