### ISSUE TITLE
four connector holes

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#117]
this board here should have same four holes as https://github.com/rusefi/rusefi-hardware/issues/227

**Comment by Nadezhda-n** [comment]
+rev. E

**Comment by rusefillc** [comment]
@Nadezhda-n нет, ревизия текущая так и не была произведена

**Comment by Qwerty-OFF** [comment]
Обновил компонент в kicad6-libraries. Пара отверстий https://github.com/rusefi/rusefi-hardware/issues/218 не перекрывала полностью отверстия в оригинальном футпринте, еще увеличил их диаметр.
