### ISSUE TITLE
rev C PPS2 voltage

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#119]
rev C on bench
using stim reference pin 11B which documentation says should be 1.1v

 ***********************************************
 * BAD channel 3 (PPS2): voltage 0.980392192 (raw 50) not in range (1.017500042..1.182500128)
 ***********************************************

**Comment by rusefillc** [comment]
Second board same rev C

 ***********************************************
 * BAD channel 3 (PPS2): voltage 0.960784384 (raw 49) not in range (1.017500042..1.182500128)
 ***********************************************

**Comment by ElDominio** [comment]
I have two more with this same issue, i am assuming this was a batch batch and some got sent out, is there a know fix?

**Comment by ElDominio** [comment]
![image](https://github.com/rusefi/hellen154hyundai/assets/5685108/e7cc441e-83ec-4598-85c8-7c11966edbab)
 
this hole is next to R126 but iBom does not show that even exists? there are traces that run to those pads?

**Comment by rusefillc** [comment]
closing issue because we have already fucked things up while unrelated issues.
