### ISSUE TITLE
aux connector silk on both sides

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#128]
do we have space to have at least some aux pinout silk?

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/hellen154hyundai/assets/4116383/8d016af3-f44f-49c6-8169-95c50a75350f)
![image](https://github.com/rusefi/hellen154hyundai/assets/4116383/e8e5ed1e-e9f3-4504-ad3f-d4937eae6cee)
