### ISSUE TITLE
X9 Digital 1 as Flex Fuel input shows 0% with 60hz PU/PD fix

### ISSUE THREAD

**Issue by ElDominio** [rusefi/hellen154hyundai#131]
I want to read flex fuel %, and I have connected a GM flex fuel sensor to pin X9. I removed the 680k pulldown, added a 1k pullup at R14, and measured the flex sensor output, which reports 60hz on an frequency multimeter. For some reason TS shows 0% flex fuel. Log and tune attached here: 
[flexlog.zip](https://github.com/rusefi/hellen154hyundai/files/13781625/flexlog.zip)

**Comment by rusefillc** [comment]
@ElDominio please use ``flexinfo`` command in console

**Comment by ElDominio** [comment]
2023-12-28_15_21_43_851: EngineState: flex counter 0
2023-12-28_15_21_43_852: EngineState: lowFlexCallbackCounter counter 0
2023-12-28_15_21_43_852: EngineState: flex freq 0.000000000
2023-12-28_15_21_43_852: EngineState: pulseWidthUs 0.000000000
2023-12-28_15_21_43_852: EngineState: latestCallbackTime 536893112
2023-12-28_15_21_43_852: EngineState: confirmation_flexinfo:8

**Comment by ElDominio** [comment]
<img width="688" alt="image" src="https://github.com/rusefi/hellen154hyundai/assets/5685108/2391383a-a408-4940-959d-6beb6bc0677b">

**Comment by rusefillc** [comment]
@ElDominio wrong resistors were touched?

we have never populated modernized rev D which you might be looking at https://github.com/rusefi/hellen154hyundai/tree/main/boards/hellen154hyundai-d


you have rev C board which visually clearly does not match the screenshot you've provided. Please share photo of REAL modified board.

**Comment by ElDominio** [comment]
![IMG_20240102_172824.jpg](https://github.com/rusefi/hellen154hyundai/assets/5685108/711d78ee-fb03-4c2a-82f3-5405ae1a182c)

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/hellen154hyundai/assets/48498823/b8c58406-aa73-42c4-9968-460bc295b56d)

![WhatsApp Image 2024-01-04 at 01 44 44_7382b29e](https://github.com/rusefi/hellen154hyundai/assets/48498823/31baca07-44d6-49ae-b4be-c2c96e46c3fc)

**Comment by rusefillc** [comment]
@ElDominio problem 
#74HC2G17GW,125
U490,
U491,

are not populated on all boards :(

**Comment by ElDominio** [comment]
They are buffers? Can i just jump pads?

**Comment by rusefillc** [comment]
```
2024-01-04_02_01_31_580: EngineState: flex counter 3708
2024-01-04_02_01_31_581: EngineState: lowFlexCallbackCounter counter 1854
2024-01-04_02_01_31_581: EngineState: flex freq 50.005001068
2024-01-04_02_01_31_581: EngineState: pulseWidthUs 17445.000000000
2024-01-04_02_01_31_586: EngineState: latestCallbackTime 536892784
```

**Comment by rusefillc** [comment]
yes buffers
yes approved to jump

X9 digital 1 are the two top pads

![WhatsApp Image 2024-01-04 at 02 02 49_5c7d6b32](https://github.com/rusefi/hellen154hyundai/assets/48498823/7ef82ece-152c-4fc2-b4ff-285aadce2574)

**Comment by ElDominio** [comment]
fix works and we have flex

**Comment by rusefillc** [comment]
@Qwerty-OFF please manually fix rev C BOM since there is a chance of rec C re-order before we go rev D

**Comment by Qwerty-OFF** [comment]
Now, the function of the dinput module is performed by the mega-module, buffers will be installed

**Comment by ElDominio** [comment]
> @ElDominio problem #74HC2G17GW,125 U490, U491,
> 
> are not populated on all boards :(

i hate 74HC2G17GW fun fact

**Comment by ElDominio** [comment]
> > [@ElDominio](https://github.com/ElDominio) problem #74HC2G17GW,125 U490, U491,
> > are not populated on all boards :(
> 
> i hate 74HC2G17GW fun fact

i now love 74HC2G17GW  and i was very dumb for saying this
