### ISSUE TITLE
At least a via for all pins

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#14]
E5
N32
E18

![image](https://user-images.githubusercontent.com/48498823/132967349-3ed47f72-57de-4538-8877-623a94b99362.png)

**Comment by rusefillc** [comment]
Also

![image](https://user-images.githubusercontent.com/48498823/132967362-061d7461-b1cf-4d58-9ea6-93fbe52e8202.png)

**Comment by Qwerty-OFF** [comment]
Done. There wasn't enough space for the E18, but we already have 14 GPIO MCUs connected to vias.
