### ISSUE TITLE
Assigning injector outputs causes FATAL on revD

### ISSUE THREAD

**Issue by ElDominio** [rusefi/hellen154hyundai#147]
![image](https://github.com/rusefi/hellen154hyundai/assets/5685108/539ce240-9f9e-4b1b-845a-d7f81df454f5)

The car ran for a while, I assigned VVT outputs and the car shut off. When I got to check, Injector and Ignition outputs are not assigned (how did it run initially?) so I assigned them, and when I assigned injectors I got that error. Car no longer runs

**Comment by Ankyth** [comment]
[testwithrevD.zip](https://github.com/rusefi/hellen154hyundai/files/15449677/testwithrevD.zip)

Wideband not working properly, erratic reading.
Tachoemeter output not working, assigned the same as it works on revB

**Comment by rusefillc** [comment]
@Ankyth should be fixed now
