### ISSUE TITLE
rev D pps2

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#151]
![image](https://github.com/rusefi/hellen154hyundai/assets/5685108/e7cc441e-83ec-4598-85c8-7c11966edbab)
 
this hole is next to R126 but iBom does not show that even exists? there are traces that run to those pads?

**Comment by ElDominio** [comment]
not revD; revC which is why i posted in the revC thread.

I was asking about revD schematics to compare if input had changed at all

Both cars read s steady voltage at pps2 input, no matter position of pps. With stock ECU pps2 reads fine (0.3v to 2v)

**Comment by rusefillc** [comment]
closing issue because we have already fucked things up while unrelated issues.
