### ISSUE TITLE
brought to you by AlphaX

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#16]
We need silkscreen of AlphaX sponsor

"Brought to you by" test
and attached logo

[logoalphax.zip](https://github.com/rusefi/hellen154hyundai/files/7148814/logoalphax.zip)

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/132993240-180f0bf6-2526-42eb-9347-62524de8c6f4.png)

**Comment by rusefillc** [comment]
Sweet!

**Comment by ElDominio** [comment]
Love it! Thanks guys
