### ISSUE TITLE
Selected engine sync input not configured

### ISSUE THREAD

**Issue by ElDominio** [rusefi/hellen154hyundai#160]
![WhatsApp Image 2024-08-21 at 18 55 28_17e77f41](https://github.com/user-attachments/assets/9902a759-8edc-4c03-8cf1-8581ec34f792)

Dealer updated ecu and car does not start. Is this the recent chaotic update?

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/issues/6830

**Comment by ElDominio** [comment]
![WhatsApp Image 2024-08-21 at 18 58 55_af174cf9](https://github.com/user-attachments/assets/dfcb5135-25ec-4fe8-a1f2-c39a14fecebb)


seems configured fine to me?

**Comment by ElDominio** [comment]
downgraded to 20240818 and problem went away

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/issues/6830 is the defect

**Comment by rusefillc** [comment]
Should be fixed now
