### ISSUE TITLE
Clutch switch input A43 does not work

### ISSUE THREAD

**Issue by ElDominio** [rusefi/hellen154hyundai#166]
There is no change on two RevD units. We swapped in a RevC and it did work.

RevC log:
[revcClutchswitchWorking.zip](https://github.com/user-attachments/files/18064147/revcClutchswitchWorking.zip)

RevD log:
[revEnonworkingClutch.zip](https://github.com/user-attachments/files/18064167/revEnonworkingClutch.zip)

I think this is only a processor pin issue, found schematics, will try lua test

**Comment by ElDominio** [comment]
![image](https://github.com/user-attachments/assets/dee5b99c-b15f-4ed5-b81c-82fa5536f06c)


Does not produce any results

**Comment by rusefillc** [comment]
@Qwerty-OFF looking for picture of PD/PU?

**Comment by rusefillc** [comment]
```
#RES2 CLUTCH: DOWN 680k 100n
R240,
R244,"680k","R0402","C163456"
C219,"100n","C0402","C307331"
```

**Comment by Qwerty-OFF** [comment]
To configure pullup you need to move the resistor
![image](https://github.com/user-attachments/assets/f0eb1d1d-76ea-48e3-8c7b-6f7ecc02f7d4)
If you can't move the small resistor, you can try adding 10k this way
![image](https://github.com/user-attachments/assets/be7824ae-664e-47b1-9db3-c06bc2409594)

**Comment by Qwerty-OFF** [comment]
Fixed in the replacements of revision E
