### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#17]
Wiring diagrams https://github.com/rusefi/rusefi/wiki/Hyundai-Genesis-Coupe

Pinout https://docs.google.com/spreadsheets/d/14IxjitlEFrC2bSp0IRdNRyXZondlvw2CmJ3Q9DUdvyo

**Comment by andreika-git** [comment]
input module: +5VA should be connected to the external net:
![image](https://user-images.githubusercontent.com/15104768/133206651-e72c6f56-1aad-4a1f-8cb6-f241305b4c31.png)

**Comment by andreika-git** [comment]
TPS1/TPS2/PPS1/PPS2 pullup/pulldown inconsistency:
![image](https://user-images.githubusercontent.com/15104768/133212718-b9e50c87-e52c-4cd0-9fb5-0eb5b4e528c4.png)

**Comment by andreika-git** [comment]
Warning: these are not hardware PWM outputs:
![image](https://user-images.githubusercontent.com/15104768/133213697-c25b98d7-d229-4be4-8251-0843d9f2bca7.png)
It may affect PWM performance because currently the firmware uses hw pwm for ETB controller...

**Comment by mck1117** [comment]
is the wastegate ETB-style? If so, it needs to be on PWM too.  If not, it's not a big deal as it's slower PWM for a solenoid.

**Comment by andreika-git** [comment]
MCU-0.4 is used but currently we have 0.5 revision:
![image](https://user-images.githubusercontent.com/15104768/133214696-5d15a4f0-72ca-4ac3-873a-ac68c725c7dd.png)

**Comment by rusefillc** [comment]
@mck1117 yes wastegate is DC motor

@andreika-git @mck1117 need help with more explicit recommendation where to connect

**Comment by andreika-git** [comment]
For example, we could use OUT_PWM2,3 for ETB and OUT_PWM4,5 for WASTEGATE. Solenoid outputs aren't used anyway (just free pads on the pcb), so they are available.

**Comment by rusefillc** [comment]
#21 created

**Comment by rusefillc** [comment]
@andreika-git is the board good enough now with recent changes?

@mck1117 is there a chance for you to review in the next 96 hours or shall I order?

**Comment by rusefillc** [comment]
ordered!
