### ISSUE TITLE
+5VA should be connected to the external net

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#19]

**Comment by Qwerty-OFF** [comment]
@andreika-git 
Aren't these pins connected?
![image](https://user-images.githubusercontent.com/4116383/133333694-dc2b50c3-6eb8-411d-97cf-5a0d05fe2b63.png)
![image](https://user-images.githubusercontent.com/4116383/133333658-c371b755-689e-479a-a071-529936409016.png)

**Comment by andreika-git** [comment]
Yes, it's connected inside the module, but it also has a TVS on that net:
![image](https://user-images.githubusercontent.com/15104768/133471098-37940e8a-df31-4d73-bb57-ddfd3c61491f.png)
The original idea was to feed +5VA to the ECU connector through the input module (and through the TVS) - to suppress higher voltage spikes (for instance, coming from VR-sensors) and make the analog supply less noisy. When the TVS is bypassed by connecting directly to the mcu's +5VA source, then it's less efficient.
Of course it's not a requirement and may not be needed for this board, so it's up to you to decide...

**Comment by Qwerty-OFF** [comment]
Good idea, but not obvious. It looks like we need to write about it here https://github.com/andreika-git/hellen-one/wiki/module-input and maybe someday when updating input module, rename this contacts to V5A_IN and V5A_OUT.

I connected external net to this pin
![image](https://user-images.githubusercontent.com/4116383/133484969-72bdb2ff-e34b-4a81-9d62-da9451182714.png)
