### ISSUE TITLE
2nd CAN bus as aux pads

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#22]
i would like this board to be a generic stm32 board with two CAN buses and two can transceivers

do we have space? do we have MCU side support with 144 pin or 176 pin?

**Comment by rusefillc** [comment]
@mck1117 will translate later

CAN1 у нас уже выведен на отдельные пины
CAN2 тоже доступен: либо на пинах SPI1 (SPI1_MOSI = CAN2_RX, SPI1_CS1 = CAN2_TX), либо SPI2 (SPI2_CS = CAN2_RX, SPI2_SCK = CAN2_TX)
Т.е. если нужен CAN2, то придётся отказаться от SPI1 или SPI2
Это справедливо и для модуля mcu (176), и mcu144

**Comment by Qwerty-OFF** [comment]
Done
