### ISSUE TITLE
CLT and IAT resistance calibration

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#28]
![image](https://user-images.githubusercontent.com/48498823/137048414-7b143670-c8d9-4cb4-8052-760ad214de77.png)

![image](https://user-images.githubusercontent.com/48498823/137048422-0d8b8293-a0ef-4de3-8370-9a36db1f2147.png)

need resistance not voltage

**Comment by mck1117** [comment]
If we can measure th pullup in a factory ecu, we can solve for R

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/137525062-178bec12-e7f5-4798-9e48-f1d7327a76d2.png)
