### ISSUE TITLE
MAP sensor calibration

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#29]
BK1
2.5bar
14.5 psi/inHg =  49.1025 kpa

![image](https://user-images.githubusercontent.com/48498823/137604013-01ddfe57-ca88-4aff-8015-ffa505330fbb.png)

BK2
3bar bosch
![image](https://user-images.githubusercontent.com/48498823/137604017-29291684-9e13-4508-bb73-f6dca3bfcf3f.png)

**Comment by rusefillc** [comment]
@ElDominio they say that 22.5 Inches of mercury = 76.1935 Kilopascals ? that does not look right for 2.5 bar sensor value too little?

**Comment by mck1117** [comment]
That's 22.5 inches of VACUUM

**Comment by blundar** [comment]
There is an old school GM 3bar from the turbo trans am that was *the* MAP
sensor to use back in the stone age.  It was a honking piece of shit as it
was only supposed to be used for the boost gauge.

There is a much newer GM 3 bar that was used on the Gen4 LS platform on the
factory forced induction cals.

I'll try to find/make a list of the OEM GM MAP sensor part numbers and
calibrations.  This would be much less ambiguous.
-D

**Comment by ElDominio** [comment]
BK1 in absolute kpa 
![image](https://user-images.githubusercontent.com/5685108/137638758-f34a4490-855f-4884-9e70-8de036889716.png)

BK2 in absolute kpa
![image](https://user-images.githubusercontent.com/5685108/137638826-3b9b237a-925b-49fe-a366-de86f1f0d3b7.png)

i have used these time and time again

**Comment by ElDominio** [comment]
Close?
