### ISSUE TITLE
Connector - latch holes are too small

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#32]
latch holes are too small for connectors I had

one alignment pin is off

second alignment pin is probably fine but under a bit of tension

image and details TBD

**Comment by Qwerty-OFF** [comment]
This footprint looks to match the documentation. Need details.

**Comment by rusefillc** [comment]
Connectors are clones, will add info on Friday

**Comment by rusefillc** [comment]
![16612706656536785912180628667518](https://user-images.githubusercontent.com/48498823/186207001-8fa90b62-2ef9-4364-9ba9-896c1cfc964f.jpg)

Add 0.7mm diameter to the highlighted holes

Enlarge all 154 or most of holes by 15%ish if possible

**Comment by Qwerty-OFF** [comment]
Fixed
