### ISSUE TITLE
Three/four green power LEDs are too bright

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#33]
green LEDs are too bright especially 3v/5v/12v

![IMG_20211016_181400](https://user-images.githubusercontent.com/48498823/137603488-02d2d343-9f50-430f-b2fc-15d3ca574ac1.jpg)

**Comment by Qwerty-OFF** [comment]
Fixed. After launching the board, update the information here https://github.com/andreika-git/hellen-one/issues/30#issuecomment-1222874214

**Comment by Qwerty-OFF** [comment]
Теперь эти светодиоды внутри модуля 5+12
