### ISSUE TITLE
crank/cam/vss are inverted

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#34]
![IMG_20211016_181400](https://user-images.githubusercontent.com/48498823/137603499-0fe0dd6d-3426-418a-afb4-f08b0246a3ca.jpg)

i would expect all three white LEDs to be off on disconnected board

**Comment by Qwerty-OFF** [comment]
Are the LEDs inverted or only on on disconnected board or both?

**Comment by mck1117** [comment]
> i would expect all three white LEDs to be off on disconnected board

the inputs have pullups, so they float high if there is no sensor/car connected...

**Comment by Qwerty-OFF** [comment]
https://github.com/rusefi/hellen154hyundai/issues/36#issuecomment-1224478505
