### ISSUE TITLE
five LEDs are dimming with IGN off and no laptop

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#35]
hook ECU to real vehicle

get 4 red and one white LED dim :(

![IMG_20211017_162957](https://user-images.githubusercontent.com/48498823/137643857-6f4d3e5d-9337-4f1e-a4e1-a7325a5a1bf5.jpg)

![IMG_20211017_162959](https://user-images.githubusercontent.com/48498823/137643859-267ba6d9-8301-4e6c-941c-b5ffcd953e3e.jpg)

**Comment by rusefillc** [comment]
@mck1117 @ElDominio FYI

**Comment by rusefillc** [comment]
@Qwerty-OFF poke we've got real users asking :)

**Comment by Qwerty-OFF** [comment]
Try to remove this:
![image](https://user-images.githubusercontent.com/4116383/160479797-654e25bb-a39e-4b2f-a3f8-feeac034da08.png)

Seems that same problem with always-hot main relay diode:
![image](https://user-images.githubusercontent.com/4116383/160479888-e93d826a-0514-4117-84e8-3cd1d93c26cc.png)

Solution for next rev:
![image](https://user-images.githubusercontent.com/4116383/160479947-d2feb56a-ddd0-4eef-8f4b-00e9c8b973d5.png)

**Comment by Qwerty-OFF** [comment]
Is it help https://github.com/rusefi/hellen154hyundai/issues/35#issuecomment-1081100280?
If so, close the ticket, fixed.

**Comment by Qwerty-OFF** [comment]
@rusefillc проблема еще есть?
