### ISSUE TITLE
CAM LEDs are killing CAM signal

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#36]
CAM signals only work once CAM LEDs are disconnected

expected: both LEDs and signal working in ECU

this issue is reproducible on the bench with "readpin PA6" "readpin PA7" commands

open question how come hellen121vag is not or less affected?

**Comment by Qwerty-OFF** [comment]
Related to https://github.com/rusefi/hellen154hyundai/issues/34
Most likely there are two solutuons: inverted LEDs or additional transistors for the LEDs to work correctly (we have space for them here).

**Comment by rusefillc** [comment]
Let's try additional transistors.

The only hard requirment is we have to be 146% sure that if we mess up we can remove aux stuff and have signal working

**Comment by Qwerty-OFF** [comment]
Added transistors. Now just like on the Nissan 121 rev с
