### ISSUE TITLE
Move fuses a bit away/offset from IGBTs to simplify hand sodlering

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#38]
at the moment fuses are too close to IGBTs so I have to put soldering iron into the gap carefully

Number 2 with offset is the easiest to solder but maybe there is a simpler way?

maybe go with smaller IGBTs like BMW 88 if we trust those?

maybe same for mercedes

![image](https://user-images.githubusercontent.com/48498823/138200276-e41c62e7-f12a-4627-9aff-f5f9c882966d.png)

**Comment by rusefillc** [comment]
https://github.com/andreika-git/hellen-one/issues/107

**Comment by Qwerty-OFF** [comment]
Changed to smaller IGBT
