### ISSUE TITLE
TLS115D0EJXUMA1 for sensor 5v

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#41]
See andreika-git/hellen-one#119

**Comment by rusefillc** [comment]
@ElDominio important known issue - at the moment 5v supply line not protected from GND or +12v

**Comment by rusefillc** [comment]
Please use SOIC package and a huge via under the chip

**Comment by Qwerty-OFF** [comment]
Done
![image](https://user-images.githubusercontent.com/4116383/186232828-1ecff4f8-ca3c-415f-ac1b-804c4bf28417.png)
![image](https://user-images.githubusercontent.com/4116383/186232878-8a3a6e7d-0300-451a-bbde-ddd62992052a.png)

**Comment by rusefillc** [comment]
Do we have space to make it dual-footprint like on some other board?

**Comment by Qwerty-OFF** [comment]
Yes, done
![image](https://user-images.githubusercontent.com/4116383/186236898-6b09d8f2-2f5b-44a3-bb26-9afbdf70350e.png)
