### ISSUE TITLE
Pin mappings non-existent VVT/WG done, PS pending

### ISSUE THREAD

**Issue by ElDominio** [rusefi/hellen154hyundai#42]
Missing some output pins in firmware

https://rusefi.com/docs/pinouts/hellen/hellen154hyundai/

No VVT:
<img width="482" alt="image" src="https://user-images.githubusercontent.com/5685108/145153770-cc244997-fed3-44de-9fca-08720bc3f78e.png">

No boost control for solenoid cars
<img width="480" alt="image" src="https://user-images.githubusercontent.com/5685108/145153811-bcc1bc4c-9e04-447a-877b-d6cc9e615173.png">

A/C is hardware on 2010-2012, CAN on 2013+. Current test car is 2013. If CAN messages are needed, I can supply them
A/C pins for 2010 aren't defined either

Power steering input is not defined, I can't see it in the pinout either, was it not added?

I'll add more as I find more things

**Comment by mck1117** [comment]
What does the power steering input do?

**Comment by ElDominio** [comment]
Shows when PS pressure go over a threshold (it's a switch at idkhowmany psi) to raise idle a bit, so it doesn't get cramped. Not the most important of pins.

**Comment by rusefillc** [comment]
@ElDominio both VVT added, fan low added, WG solenoid added - it's yours to test

todo PS switch a bit later

**Comment by rusefillc** [comment]
Closing for now
