### ISSUE TITLE
Alternator Control

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#43]
@ElDominio is alternator charging? We have nothing hooked to pin 46 what is pin 46 doing?

**Comment by ElDominio** [comment]
That's exactly how i've wired everything up before, the alternator just defaults to 14v in that case. I ran it for a while with no charger and it ran fine but I'll confirm just in case tomorrow

**Comment by ElDominio** [comment]
Just checked: it is running in failsafe mode. As soon as I get useable RPM's, voltage goes straight to 13.8 and stays there

**Comment by rusefillc** [comment]
Acceptable? Good? Bad?

**Comment by ElDominio** [comment]
That's perfect IMO
