### ISSUE TITLE
Document Aux IO - rev C

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#44]
fuel pressure - analog input, hard but possible
o2 sensor - why analog input? big boys should do CAN

flex - digital input very possible
boost control - huh?
nitrous solenoid - possible by adding transistor on proto area or changing next revision of board

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/146446048-27d9e289-34ac-4326-b365-073738957c85.png)

![image](https://user-images.githubusercontent.com/48498823/146446513-b96e7dc2-efd4-44b2-b147-62547aa18298.png)

**Comment by rusefillc** [comment]
Looks like in order to get aux analog input we should move CAM2 input from analog-capable AUX4 to SENS2 maybe?

**Comment by rusefillc** [comment]
@ElDominio
TL,DR analog inputs is hardest we can MAYEB squeeze in if we add a jumper wire on the board let me know if needed. we use OEM oil pressure on the board which we do not use, your call if you are ready to start repurposing those channels which do not really have software support at the moment

we have a few logic level outputs and we have proto area to make those into full blown high current outputs. it sounds like you are interested in this as an improvement in next revision

flex input being digital input should be possible just need to test

**Comment by ElDominio** [comment]
The thing is most clients are interested in adding stuff later down the road, so at least on the PNP LinkECU boards I had designed, I added a 12pin Molex MiniFit to provide for additional IO. The test car currently has an additional fuel pump, has flex sensor, a WB02 and an extra switch wired into this.

https://www.alphaxpr.com/collections/alphax-line/products/genesis-coupe-2-0t-pnp-harness-for-linkecu on the left side
