### ISSUE TITLE
Let's remove some jumpers in order to get space on the board

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#45]
![image](https://user-images.githubusercontent.com/48498823/146451722-056559a0-c1c2-4773-8b21-f1c50e46e380.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/146451844-93d211e2-b2f5-4154-b5f3-90c0993c78a2.png)

![image](https://user-images.githubusercontent.com/48498823/146451890-7f801fce-a4d6-4317-9ca6-0144f557f402.png)

![image](https://user-images.githubusercontent.com/48498823/146451945-af6ea457-9954-4b4c-ac07-3de45d8792af.png)

**Comment by rusefillc** [comment]
@ElDominio please review and confirm that those onces here are SOLID

**Comment by ElDominio** [comment]
SOLID meaning they work?

If so yes, all of these work

**Comment by rusefillc** [comment]
SOLID as "there is no way on earth I would need to mess with those traces mentioned above, those would always be the default pinout as on current board"

**Comment by ElDominio** [comment]
Yep, definitely solid then

**Comment by Qwerty-OFF** [comment]
Done
