### ISSUE TITLE
Some digital inputs are using analog inputs

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#46]
Analog inputs are hot commodity we should free those from digital inputs

![image](https://user-images.githubusercontent.com/48498823/146469685-7dac67f2-4103-4de7-b903-9787ca399797.png)

**Comment by rusefillc** [comment]
@ElDominio which of these are analog or on/off digital:

ac_on
clutch
brake
ac_pressure

**Comment by ElDominio** [comment]
only AC pressure is voltage, others are switched

**Comment by rusefillc** [comment]
@ElDominio do you know if those need pull-up, i.e. are those GND/floating on the wire or voltage/GND or else?

**Comment by ElDominio** [comment]
Brake is 12/gnd
clutch is gnd/floating
ac i don't clearly remember, i think it's gnd floating since it's only a request
ac pressure is voltage 0-5

**Comment by Qwerty-OFF** [comment]
@rusefillc RES1-RES3 is not analog (https://github.com/andreika-git/hellen-one/wiki/module-input). Should I do anything?

**Comment by rusefillc** [comment]
We should move Crank/cam1/cam2 to digital-only pins and have current "crank/cam1/cam2" available as analog.

(overall the big picture: we've made a mistake while selecting default crank/cam - those should never be using analog-capable pins)

**Comment by Qwerty-OFF** [comment]
Done https://github.com/rusefi/hellen154hyundai/issues/48#issuecomment-1224642038
