### ISSUE TITLE
Repropose RCV control as aux out No 1

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#47]
At the moment we have x8 of PWM drivers

x4 injectors + x2 VVT + x1 BK1 WG solenoid + x1 RCV

Do we want to remove R31 and convert that channel into AUX PWM driver No 1?

![image](https://user-images.githubusercontent.com/48498823/146479887-ccedb4bd-6fe7-4869-b19a-725cb78a75f6.png)

**Comment by ElDominio** [comment]
Honestly, no one uses RCV. The reason some people include it is for stock compatibility reasons. Honestly no one has a stock BPV anymore

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/186236564-36891ff3-6b0f-49ad-a0ab-a0ff4484955b.png)
