### ISSUE TITLE
Suggested auxiliary pins; and confirmed pins that don't need jumpers

### ISSUE THREAD

**Issue by ElDominio** [rusefi/hellen154hyundai#48]
Suggest aux pins:
12v
5v
gnd
flex see https://github.com/andreika-git/hellen-one/issues/123
boost duty output
nitrous output
some ground switch (so people can put a switch to do something
fuel pressure 0-5v
oil pressure 0-5v

all confirmed working IO
ETB
VVT1/2
all fuel injectors
all ignition outputs
cam/crank
MAP1
CLT
IAT

I did not check MAP2 (could be used as Baro)

**Comment by ElDominio** [comment]
to update this list:

recommend using LCSC part number  C477839

![image](https://user-images.githubusercontent.com/5685108/185768056-02a9f4cf-0173-4449-b168-34b1206dc480.png)

Pins are as follows:
1. 5V source
2. 0-5v p1
3. 0-5v p2
4. digital input p1
5. Ground PWM p1
6. digital input p2
7. 12v source
8. 0-5v p3
9. digital input p3
10. ground pwm p2
11. ground pwm p3
12. sensor ground

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/186242257-c985929b-59e6-4c97-93f5-91ea0633af2b.png)
@ElDominio please check (reverse numbering of contacts is a feature of the footprint)

**Comment by rusefillc** [comment]
@Qwerty-OFF: Norman says "Anywhere is fine"

but we have case shape considerations

maybe here?

![image](https://user-images.githubusercontent.com/48498823/186256835-d2ae84b9-d58a-43c7-9088-c0b949f9ba70.png)

**Comment by rusefillc** [comment]
PS: new ETB drivers can go on the back side of the PCB I guess if that would help at all?

We might get double sided inputs and outputs modules in the next few days if that would help

**Comment by ElDominio** [comment]
Are there pins available to give exclusive use to the pins I stated in the comment? (not shared with anything on main connector, only dedicated for AUX use)

**Comment by rusefillc** [comment]
See https://github.com/andreika-git/hellen-one/issues/155

**Comment by Qwerty-OFF** [comment]
> recommend using LCSC part number C477839

This is right angle connector, is it possible to place it in the center of the board, and not on the edge? Should I use the same straight connector?

> Are there pins available to give exclusive use to the pins I stated in the comment? (not shared with anything on main connector, only dedicated for AUX use)

AUX_LS1 connected to OUT_WGT on main connector. If need seems possible place additional MOSFET for AUX_LS1.

How much current should the AUX pins support?

**Comment by rusefillc** [comment]
let's use VND7/VND14NV04TR "DPAK-3","C155605"

**Comment by rusefillc** [comment]
Please add pull-up/pull-down instructions for all aux analog inputs on the back of the PCB

**Comment by rusefillc** [comment]
@ElDominio says to use vertical molex connector

**Comment by Qwerty-OFF** [comment]
> use vertical molex connector

OK

> pull-up/pull-down instructions

![image](https://user-images.githubusercontent.com/4116383/187036565-83688271-223e-459b-ace1-b6b9244535c4.png)
