### ISSUE TITLE
relay output for 2nd fuel pump

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#50]
We want to active 2nd fuel pump relay  when at 4kRPM OR 15psi - it would be Lua since combined logic

open question where to we add that wire?

**Comment by rusefillc** [comment]
We have https://github.com/andreika-git/hellen-one/wiki/module-output

we have a lot of outputs available

![image](https://user-images.githubusercontent.com/48498823/146627325-b35dce4f-0373-4829-aa62-bbc7bd077a96.png)

**Comment by rusefillc** [comment]
@ElDominio let's use P69 I will now make it available in TS

![image](https://user-images.githubusercontent.com/48498823/146627406-c68a01e1-f151-467b-bd23-4ce7f4f6d329.png)

**Comment by Qwerty-OFF** [comment]
@rusefillc should I do anything?

**Comment by ElDominio** [comment]
This is also fine if routed to aux connector.

**Comment by rusefillc** [comment]
we can add up to aux 10 outputs it's the question of level of effort

**Comment by rusefillc** [comment]
Sounds like one of low side aux ouputs
