### ISSUE TITLE
reuse WG solenoid wiring for BK2

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#51]
Any side of R30 could be used to add an extra wire for aftermarket WG solenoid

![image](https://user-images.githubusercontent.com/48498823/146627592-fd93bcb2-4cb5-4ae5-b14c-7d9e6bc46219.png)

**Comment by rusefillc** [comment]
@ElDominio do we need this open or time to close?

**Comment by ElDominio** [comment]
Will the aux port (molex) I mentioned be implemented? If so, it would obviate this since we can use one of those PWM outputs

**Comment by rusefillc** [comment]
Do we have molex ticket for this hellen154hyundai?

**Comment by ElDominio** [comment]
#48

**Comment by Qwerty-OFF** [comment]
Done
![image](https://user-images.githubusercontent.com/4116383/186243473-2ac9057e-659f-4039-96c5-b4818d95e326.png)

**Comment by rusefillc** [comment]
let's have R30 DNP

**Comment by rusefillc** [comment]
Let's add schematics note next to main connector just to clarify that on main connector it's "OEM BK1" 

We want same trace/output to be routed to aux connector for BK2 people to use it if desired without adding a wire into OEM harness

**Comment by rusefillc** [comment]
STATUS UPDATE: let's actually DETACH OUT_WG_BK1 from aux connector

please let's have all aux connector low sides have nothing to do with main connector outputs

overall the idea is to not confuse user support between BK1 and BK2, much safer to have consistent story and just ignore unused OUT_WG_BK1 on BK2 vehicles

**Comment by Qwerty-OFF** [comment]
Done
