### ISSUE TITLE
Pin 84 (O2 Signal) should be to an analog voltage 

### ISSUE THREAD

**Issue by ElDominio** [rusefi/hellen154hyundai#52]
Connecting this pin to an analog voltage input on the ECU would allow the use of this wire as an O2 input for people running widebands. Connect pin 84 to an analog input on the processor? With proper conditioning for 0-5v?

**Comment by rusefillc** [comment]
Some sort of a jumper into one of aux analog inputs @ElDominio ?

**Comment by ElDominio** [comment]
If we're short on analog inputs, sure

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/186978346-add0e212-5eb5-43b5-af1a-f27c922b7d59.png)
AIN3 for IN_WBO or AUX analog. Close if ok

**Comment by rusefillc** [comment]
Looks good to me!
