### ISSUE TITLE
AC Request not working on BK1

### ISSUE THREAD

**Issue by ElDominio** [rusefi/hellen154hyundai#54]
I tried on a BK1, seems the pin is floating? On "default" it thought it was on (apprently no voltage at pin) and I activated the pullup and it turned off. Physical button did no change.

It also activates while starting? Tune and log on rusefi online

**Comment by rusefillc** [comment]
I assume
https://rusefi.com/online/view.php?msq=939
and
https://rusefi.com/online/view.php?log=737 https://rusefi.com/online/view.php?log=736

**Comment by rusefillc** [comment]
just a reminder about rusEFI console "live data" view

let me try that "live data" for AC control on my NB2 tomorrow

**Comment by ElDominio** [comment]
Correct, let me know so I can test further

**Comment by ElDominio** [comment]
Tested this, no change on anything on liveview

**Comment by rusefillc** [comment]
please update to latest firmware with "view" in .ini

and post a fresh log reproducing the problem

**Comment by ElDominio** [comment]
[2022-06-28_14.41.19.mlg.zip](https://github.com/rusefi/hellen154hyundai/files/9004930/2022-06-28_14.41.19.mlg.zip)

no change is detected, im pressing the button every which way

**Comment by rusefillc** [comment]
RPM=0 means "engine is too slow to enable A/C". This log works as expected?

Note "view->AC" dialog - i assume it would show which condition is YES while all other conditions are NO?

![image](https://user-images.githubusercontent.com/48498823/176991751-407cd953-3884-4be5-acdf-46aad0b70bc9.png)

![image](https://user-images.githubusercontent.com/48498823/176991829-a32d64b6-91cc-48c6-b298-fc424adc3947.png)

**Comment by ElDominio** [comment]
I was pressing the a/c button on/off like 10 times and there is no change anywhere, I should at least be able to see a change of state on A/C request even if the compressor won't engage because of software conditions

**Comment by rusefillc** [comment]
Ohhhh

Well, we've made progress i finally understand the problem statement!

**Comment by rusefillc** [comment]
@ElDominio do we believe that A/C request is pin 57 of 60 pin connector?

![image](https://user-images.githubusercontent.com/48498823/177019071-fef6e6a9-0add-4afe-bd9f-17065bfb868f.png)

@Qwerty-OFF what do we have for pull-up/pull-down on that RES input?

![image](https://user-images.githubusercontent.com/48498823/177019104-933d085a-98e2-4183-8056-3f01d585c9c5.png)


![image](https://user-images.githubusercontent.com/48498823/177019101-022145a7-6c05-44cc-8ce7-5c1f6b39639f.png)

**Comment by rusefillc** [comment]
@Qwerty-OFF says's 680k to 5V

that sounds too low to me

please add 10K resistor between "inner" side of R57 jumper and 5v point anywhere on the prototying area

**Comment by ElDominio** [comment]
Pin 57 measures 4.7ish volts with AC OFF, 11.3ishvolts with AC ON

**Comment by rusefillc** [comment]
@Qwerty-OFF would a voltage divider get values into stm32 TTL range?

**Comment by Qwerty-OFF** [comment]
@rusefillc its possible if needed

**Comment by ElDominio** [comment]
Will check tomorrow, was tested with rusefi.

**Comment by Qwerty-OFF** [comment]
> R57
Typo, R58, not R57...

It looks like it's a high side button. Try to remove pullup and place pulldown.

**Comment by ElDominio** [comment]
No ecu results:

0v when off
12v when on

I assume I had left pullup on RusEFI for some reason; but disabling it still does not make the behavior work as expected

**Comment by rusefillc** [comment]
@ElDominio please clarify if 10K was added anywhere maybe with a picture

please note the correction in where 10K needs to be added it's now R58 for pin 57

**Comment by ElDominio** [comment]
Completely forgot, writing this message to remind myself to do it while I have a BK1 at the shop

**Comment by Guelphgenesis666** [comment]
Any one have any pics of where to place 5k resistor between r58 and 5v point

**Comment by rusefillc** [comment]
@Guelphgenesis666 please use proto area

just check that pads are not connected to each other since those are paired or tripled

![image](https://user-images.githubusercontent.com/48498823/182100504-6641bc7c-3b87-4ea4-be9d-fae2e0fc11d8.png)

**Comment by Guelphgenesis666** [comment]
So just connect resistor to 5v pad and then other end to r58?

Sent from my iPhone

On Aug 1, 2022, at 3:55 AM, rusefillc ***@***.***> wrote:

﻿

@Guelphgenesis666<https://github.com/Guelphgenesis666> please use proto area

just check that pads are not connected to each other since those are paired or tripled

[image]<https://user-images.githubusercontent.com/48498823/182100504-6641bc7c-3b87-4ea4-be9d-fae2e0fc11d8.png>

**Comment by rusefillc** [comment]
yep

maybe post a photo before turning power back on :)

**Comment by rusefillc** [comment]
photo above is the correct way to do "please add 10K resistor between "inner" side of R57 jumper and 5v point anywhere on the prototying area" as requested at https://github.com/rusefi/hellen154hyundai/issues/54#issuecomment-1172979692


it looks like https://github.com/rusefi/hellen154hyundai/issues/54#issuecomment-1178231342 is suggesting to do pull-down instead which would mean resistor to GND not +5v

overall I am pretty confused for sure but you are pretty close :)

@qwerty-off FYI

**Comment by Guelphgenesis666** [comment]
> @ElDominio please clarify if 10K was added anywhere maybe with a picture
> 
> please note the correction in where 10K needs to be added it's now R58 for pin 57

This says r58 . And that is a 10k resistor I’m
Using. Do I need to move it to here instead? 
![Uploading 14FC03C9-4C99-4845-AB3D-31B93A25159D.jpeg…]()

**Comment by Guelphgenesis666** [comment]
![Uploading 708F5AA3-A1A9-4B70-ABF0-6B40E070A3B6.jpeg…]()

**Comment by rusefillc** [comment]
@Guelphgenesis666 this github here is not the best chatting platform, note the missing images. with too much gaps between communications I am forgetting context. we need to find a different way to get in touch when we both have time to get more efficient.

**Comment by Guelphgenesis666** [comment]
Here’s my email If you can send me a msg. J.p.ouellette@hotmail.com

**Comment by rusefillc** [comment]
@ElDominio please test with 10K between lower side of R58 and GND, half like the picture

**Comment by Guelphgenesis666** [comment]
I added the 10 K resistor between the lower side of R58, And ground, Using pulldown AC switch mode, I am now seeing the AC request when I hit the ac button. Just going to Solder The resistor in place so I can reassemble the ECU and go test drive. I’ll let you guys know in an hour or so
![B6ECB2CA-659B-4D50-B088-8B3F3D73E74F](https://user-images.githubusercontent.com/109481626/183306592-23ec0984-70bb-4f0f-b913-5a4f2ef366d6.jpeg)

**Comment by Guelphgenesis666** [comment]
![Uploading CB052287-6DB6-41CB-A7BE-CC6B8617A539.jpeg…]()

**Comment by Guelphgenesis666** [comment]
No power to the ac compressor clutch. Tuner studio shows the button being pressed and says ac is on, however there’s no power to the compressor clutch

**Comment by rusefillc** [comment]
so AC request is fixed?

@ElDominio had BK2 A/C working with CAN bus A/C request so BK2 ac compressor clutch is good? are there any differences between BK1 and BK2?

**Comment by Guelphgenesis666** [comment]
![00C436B1-58EE-49F6-90E9-E1A22CC69CA8](https://user-images.githubusercontent.com/109481626/183315805-61a1d0d9-c1fd-445e-8a6e-f6076bfac00c.jpeg)

**Comment by rusefillc** [comment]
@Guelphgenesis666  looks like A/C output not configured?

@ElDominio what should it be for BK1? what should it be for BK2? do you have a link to your working BK2 tune?

![image](https://user-images.githubusercontent.com/48498823/183316153-8cd9fb97-99d8-4039-84e0-a1d9ebac088a.png)

**Comment by Guelphgenesis666** [comment]
How do I configure it. What settings do I need?

Sent from my iPhone

On Aug 7, 2022, at 7:57 PM, rusefillc ***@***.***> wrote:

﻿

@Guelphgenesis666<https://github.com/Guelphgenesis666> looks like A/C output not configured?

@ElDominio<https://github.com/ElDominio> what should it be for BK1? what should it be for BK2? do you have a link to your working BK2 tune?

[image]<https://user-images.githubusercontent.com/48498823/183316153-8cd9fb97-99d8-4039-84e0-a1d9ebac088a.png>

**Comment by Guelphgenesis666** [comment]
I set ac relay to “k87 ac relay” . What do I need for ac relay mode

Sent from my iPhone

On Aug 7, 2022, at 7:57 PM, rusefillc ***@***.***> wrote:

﻿

@Guelphgenesis666<https://github.com/Guelphgenesis666> looks like A/C output not configured?

@ElDominio<https://github.com/ElDominio> what should it be for BK1? what should it be for BK2? do you have a link to your working BK2 tune?

[image]<https://user-images.githubusercontent.com/48498823/183316153-8cd9fb97-99d8-4039-84e0-a1d9ebac088a.png>

**Comment by rusefillc** [comment]
default should be good. please power cycle ECU just to make sure setting is applied

**Comment by ElDominio** [comment]
Can confirm, resistor jumped from gnd to R58 fixes the issue.

**Comment by rusefillc** [comment]
@Qwerty-OFF we would need schematics chagne here

note that only half of units ("first generation BK1") would be using those so we would at least need a comment on the schematics

**Comment by Qwerty-OFF** [comment]
Fixed
![image](https://user-images.githubusercontent.com/4116383/186248715-cf1aaf6c-d55d-40f5-b0af-57a4275de1bb.png)
![image](https://user-images.githubusercontent.com/4116383/186248890-f82216be-b252-4bd3-a0a8-c0d7e67c7859.png)
