### ISSUE TITLE
L6205PD is too weak to run ETB in single channel configuration

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#55]
we have to move to dual 9201

in the meantime would need to hack current boards to make it match nissan

inputs you can cut a trace and just short those

![image](https://user-images.githubusercontent.com/48498823/162863025-ad863430-2d83-4b8e-93d7-71522a5013b3.png)

**Comment by Qwerty-OFF** [comment]
Connect together 45+132 and 60+131
![image](https://user-images.githubusercontent.com/4116383/162997817-a57b65e5-87a5-4baf-8722-215b3eb7b1e0.png)
Cut this (or set to Hi-Z/Input wastegate pins on STM32):
![image](https://user-images.githubusercontent.com/4116383/162998766-c6195ef5-7e14-4697-be75-0d3346c3ad88.png)
Connect this:
![image](https://user-images.githubusercontent.com/4116383/162999088-bc925f56-9ef3-47e7-b6d7-26b647beea06.png)

**Comment by rusefillc** [comment]
Does it have to be diagonal? Is there a way to connect pin 6 to pin 7 and pin 14 to pin 15?

![image](https://user-images.githubusercontent.com/48498823/163210621-6a69d4b1-762d-41a5-acfc-2759bb8df439.png)

**Comment by Qwerty-OFF** [comment]
It is possible, but in this case the maximum current will be two times lower

**Comment by rusefillc** [comment]
See https://github.com/rusefi/hellen154hyundai/issues/56

**Comment by mck1117** [comment]
> It is possible, but in this case the maximum current will be two times lower

huh? why? Paralleling the two channels will double the current capacity, and halve the on-resistance (halving the heat!).

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/163421203-e473fc65-29cc-43e8-8159-041a0be55028.png)
![image](https://user-images.githubusercontent.com/4116383/163421298-86e586ed-b879-4089-90c4-93e954705db3.png)
Internal current sensor placed only on high-sides:
![image](https://user-images.githubusercontent.com/4116383/163423264-ed47cbf8-9240-4cd9-8c24-76fc4ea2d04e.png)
and work independent in part A and B, but sum currents from both high-sides of part

**Comment by mck1117** [comment]
Ah, I see, the question is whether you do 1A1B + 2A2B vs. 1A2A + 1B2B. I agree, the diagonal way is superior to adjacent pins. However, we still get some of the benefit doing the "adjacent way", since that still reduces Rds_on, while not increasing the current limit. I'm reasonably sure we're hitting the thermal cut rather than the hard current limit.

**Comment by Guelphgenesis666** [comment]
For this step: Connect 45/R57 with 132/R45 and 60/R60 with 131/R44.  
do the wires need to extend outside the ecu housing or just connect the wires r57 with r45 and r60 with r44

**Comment by rusefillc** [comment]
Nothing goes outside of the ECU

just a jumper wire from PCB to PCB, it's just the picture shows it going out for clarity

I am failing to find my reference photos of when I did the mod myself :( @ElDominio do you have any pictures?

**Comment by Guelphgenesis666** [comment]
i added the 2 jumper wires , scratched through the 2 tracer wires , now I just need to connect pcb to pcb. That all that’s needed?

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/179421025-2a1ce40f-4132-4c42-be0c-ea90d225a5c8.png)

not the best photo but you can see the blue wire and a short piece of the green wire in the top-left corner just to give you the idea

**Comment by rusefillc** [comment]
correct

please post a pic of what you've done

**Comment by rusefillc** [comment]
PS: there was no need to scratch, software was taking care of traces

**Comment by Guelphgenesis666** [comment]
This step [image0.png]

Sent from my iPhone

On Jul 17, 2022, at 3:10 PM, rusefillc ***@***.***> wrote:

﻿

correct

please post a pic of what you've done

**Comment by rusefillc** [comment]
@Guelphgenesis666 please try again but give it more time to upload the image

**Comment by Guelphgenesis666** [comment]
![F56ADCFA-61F6-4B77-B4D7-7F353E1D963D](https://user-images.githubusercontent.com/109481626/179422425-9ff36506-ad35-4f0d-ba81-6abd0a96cfc6.png)

**Comment by rusefillc** [comment]
@Qwerty-OFF please migrate to two TLE9201

**Comment by Qwerty-OFF** [comment]
Done
![image](https://user-images.githubusercontent.com/4116383/186271919-a218da5b-e7fc-4929-8a22-a742a0a2d18d.png)
