### ISSUE TITLE
Exhaust VVT angle jumps from 0 to 359.1 while craking.

### ISSUE THREAD

**Issue by ElDominio** [rusefi/hellen154hyundai#57]
Tuning a car, I added CAM sync stuff to enable VVT, the car lost sync and wouldn't even start correctly. Settting cam sync to inactive would still be impossible to start, had to disable injection to clear flood.

I suggest removing first/second half settings and only having a half moon setting, then allowing a +/-360 degree offset
[My Big Turbo Meth 1500cc.zip](https://github.com/rusefi/hellen154hyundai/files/9286092/My.Big.Turbo.Meth.1500cc.zip)

tune and logs attached

**Comment by rusefillc** [comment]
it looks like with your current offset your position was too close to 360, and above 360 puts you into negative position

can you substract 360 from offset to get closer to zero position?

![image](https://user-images.githubusercontent.com/48498823/183549094-6563a973-c27c-4dcf-9cfb-5873d3105f37.png)

**Comment by rusefillc** [comment]
just a reminer that "intake" cam is the important one, that one controls engine phase
the other one which we call "exhaust" should not affect engine phase

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/183738765-f98590fb-185c-42a0-82be-c430d5c0ac36.png)

**Comment by ElDominio** [comment]
Things we have learned:
![image](https://user-images.githubusercontent.com/5685108/183742741-d568fa4a-5920-4537-823c-0da13d9208c3.png)

-Having  "maximum cam/vvt sync RPM" to a value slightly above cranking makes the decoder go crazy and start changing values from positive to negative, it needs to be over idle if it is even being used.

-still don't understand what is the difference between "single tooth first/second half" and why can't we just offset crank trigger by 360

-Tunerstudio is not accepting any values in this table:
![image](https://user-images.githubusercontent.com/5685108/183744058-302a2ffb-da90-4aed-92c7-d9baa84cc5c1.png)

**Comment by rusefillc** [comment]
@ElDominio i see the table values defect let me fix

**Comment by rusefillc** [comment]
https://github.com/rusefi/ts-issues/issues/52

**Comment by ElDominio** [comment]
[https://youtu.be/pd6hGU-FxDA]() example of issues. Starts fine once, then after shutting down it will never restart since apparently vvt angle changes sync point

**Comment by rusefillc** [comment]
@ElDominio I am just a java developer with pretty limited abilities

being far from the vehicle I need tune which matches video and logs matching video as a starting point to even have a chance to help

**Comment by ElDominio** [comment]
That matches yesterday's tune and log

**Comment by rusefillc** [comment]
@ElDominio please call when you have a chance

**Comment by ElDominio** [comment]
https://user-images.githubusercontent.com/5685108/184249421-e29716b9-266d-4f83-85cc-ffb307757b98.mp4

Video log log5camfirst and log2camfirst tune

**Comment by ElDominio** [comment]
https://user-images.githubusercontent.com/5685108/184249510-06843676-243f-41be-8e1a-eb4b94f1de49.mp4

Video of log4cam.log and log1cam.msq

**Comment by ElDominio** [comment]
Video of log3cam.log and log1cam.msqhttps://user-images.githubusercontent.com/5685108/184249645-8b0a881c-446f-4500-978d-6474520addcc.mp4

**Comment by ElDominio** [comment]
Tune and logs at https://rusefi.com/online/index.php?vehicleName=raymond&user_id=675&sorts[uploadedMsq]=-1&sorts[uploadedLog]=-1

**Comment by ElDominio** [comment]
Log1cam.msq is set to second half, log2camfirst is set to first half

**Comment by rusefillc** [comment]
this one looks like VVT is happy, decoded intake position is close to zero. around 750 RPM at low RPM car starts to die and maybe as a result of car shutting down intake position goes a bit crazy. 

I suspect that intake VVT here is consequiece not cause of car dieing

https://rusefi.com/online/view.php?log=958

![image](https://user-images.githubusercontent.com/48498823/184253780-89dc61ab-bf5d-4ac1-ab20-e2bcdbb06c29.png)

**Comment by rusefillc** [comment]
Separate story https://github.com/rusefi/rusefi/issues/4433

**Comment by ElDominio** [comment]
Logs at:

https://rusefi.com/online/view.php?log=985
Can be seen at 2s

https://rusefi.com/online/view.php?log=986
Can also be seen at 2s

**Comment by mck1117** [comment]
this is probably the same-ish thing as https://github.com/rusefi/rusefi/issues/4463 and/or https://github.com/rusefi/rusefi/issues/4459

**Comment by ElDominio** [comment]
Close
