### ISSUE TITLE
crank & cam test points silkscreen

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#58]
![image](https://user-images.githubusercontent.com/48498823/186217581-416c91e8-5209-4b89-ba2f-4be127391472.png)

please add "cam1", "cam2" and "crank" text to current P76/P77/P78

Please make sure same silk on both sides of the board

**Comment by Qwerty-OFF** [comment]
Done
![image](https://user-images.githubusercontent.com/4116383/187035857-36ef157a-6701-4a67-b495-810c8d296dee.png)
![image](https://user-images.githubusercontent.com/4116383/187035874-1012200a-0aca-4c02-95d4-35a89c2ff2e8.png)
