### ISSUE TITLE
Odd readout in Console, hellen154hyundai set as 60/2 

### ISSUE THREAD

**Issue by ElDominio** [rusefi/hellen154hyundai#60]
![image](https://user-images.githubusercontent.com/5685108/186779781-7c3092bf-681c-4662-a1d8-17728ae6cbf5.png)

The car pretty much runs like the picture shows (one cylinder?) 

Log: https://rusefi.com/online/view.php?log=1000

**Comment by rusefillc** [comment]
I do not see one cylinder on the picture :( Do you have "show only trigger" or whatever is that checkbox enabled?

**Comment by ElDominio** [comment]
"focus on inputs" was selected, my bad

![image](https://user-images.githubusercontent.com/5685108/186781576-df52939a-0b19-4c68-b77b-a0aa714f16f3.png)

**Comment by ElDominio** [comment]
In individually wired wasted, it runs _better_ but the car still misfires

![image](https://user-images.githubusercontent.com/5685108/186782622-bae19c1d-7b1f-4f3b-af4a-979fc9b7fea4.png)

**Comment by mck1117** [comment]
can you try some old firmware and see if it's different/better/worse?

**Comment by ElDominio** [comment]
On july 3

![image](https://user-images.githubusercontent.com/5685108/186783685-80dab3bb-0864-4350-984d-4bf0ea010ea2.png)


Same, car is misfiring quite a bit at idle

**Comment by mck1117** [comment]
did this car not do this before, but does now? seems like car hardware problem

**Comment by rusefillc** [comment]
Sounds like time to https://github.com/rusefi/rusefi/issues/4485

**Comment by rusefillc** [comment]
@ElDominio did we ever hard-code a somewhat good tune to at least star a car? or is this one very not OEM?

**Comment by mck1117** [comment]
> Sounds like time to [rusefi/rusefi#4485](https://github.com/rusefi/rusefi/issues/4485)

the trigger looks pretty okay to me, but it certainly can't hurt

**Comment by ElDominio** [comment]
This car runs perfectly fine on a Haltech PNP though, I just swapped it in and it runs perfectly.

I recorded videos of both but you can only hear crickets lol

**Comment by mck1117** [comment]
timing similar? fuel pulse width similar? throttle position similar?

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/186785077-8e6998ad-b638-4685-a415-c500bafa5106.png)
 for reference
 
 I'll see if i can make it run similarly (this runs seq ignition i know it barely makes a difference)

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/186785771-3d68790c-3d7f-4c28-b63a-8ea4ae4c27f4.png)


WIth these values it's idling extremely lean, even though pulsewidth it .3ms more

**Comment by mck1117** [comment]
are we sure the other ECU is running sequential fuel? is it making 2 pulses per cycle or 1?

**Comment by ElDominio** [comment]
1 pulse per cylce, can scope it if you need (pnp Haltech comes locked to Sequential anyways)

**Comment by ElDominio** [comment]
Idk, after running for a while seems fine, still running individually wired wasted btw

**Comment by rusefillc** [comment]
Just pushed global spark and injection counters into logs https://github.com/rusefi/rusefi/commit/cecc5a9d6e7614f94aee6edaaab32fc9a97d1df1 just to have more, more, MORE data in the logs

**Comment by ElDominio** [comment]
Close
