### ISSUE TITLE
SOT-223 part number change - double-check main tab pinout

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#61]
hellen-outputs has largest SOT-223 tab unconnected due to potentially incompatible pinout of the largest tab

@Qwerty-OFF please be aware of https://github.com/rusefi/hellen154hyundai/commit/4eb2225369194825d01946217f45866a3d851190

**Comment by Qwerty-OFF** [comment]
Now these transistors are only used inside hellen.  Others replaced by VND14 https://github.com/rusefi/hellen154hyundai/issues/48#issuecomment-1228862172
