### ISSUE TITLE
J2 BOM

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#62]
row spacing and pitch, somtimes it's square 4.2 sometimes it's not

![image](https://user-images.githubusercontent.com/48498823/187922784-db7074bf-7675-46d4-ba19-699511f874ba.png)

**Comment by rusefillc** [comment]
C239476 is square would NOT work for us? @Qwerty-OFF 

https://jlcpcb.com/partdetail/238580-C4201WVA2x6P/C239476

**Comment by rusefillc** [comment]
@Qwerty-OFF same story C388775 

https://jlcpcb.com/partdetail/XkbConnectivity-X9357WV_2x06HNN2SN/C388775

I am confused. Current PCB wants 5.5 row spacing right?

**Comment by Qwerty-OFF** [comment]
C239476:
![image](https://user-images.githubusercontent.com/4116383/187935400-fc1bb282-6eff-47f0-abbf-9f11ea8c37e4.png)
C388775:
![image](https://user-images.githubusercontent.com/4116383/187935560-43ebfb21-05da-405a-8897-a487668e8994.png)


> Current PCB wants 5.5 row spacing right?

Yes
