### ISSUE TITLE
At least some silk for aux molex connector

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#66]
GND/5v/etc what can we fit on top or back?

![image](https://user-images.githubusercontent.com/48498823/196054783-9916a7a1-4f07-48bc-8b13-09194980411a.png)

**Comment by rusefillc** [comment]
Same as https://github.com/rusefi/hellen121nissan/issues/27

**Comment by Qwerty-OFF** [comment]
Duplicate #128
