### ISSUE TITLE
ibom is not happy around Q1

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#68]
No package data?

https://rusefi.com/docs/ibom/hellen154hyundai-c-ibom.html

![image](https://user-images.githubusercontent.com/48498823/198423304-dcdfe46c-f787-4d0d-805a-62252fd78e08.png)

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/hellen154hyundai/assets/4116383/9ddcfd86-b704-4f13-bc97-13e3615d392c)
