### ISSUE TITLE
 Incorrect serial signature?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/hellen154hyundai#70]
![image](https://user-images.githubusercontent.com/5685108/198493038-80104b70-8cf8-48cb-9207-1f267d37b6a1.png)

Incorrect serial signature?

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/198493772-390a3443-27f0-48b8-8768-3ab82321c009.png)

it's me working on something
