### ISSUE TITLE
Manual BOM fixes on rev C boards

### ISSUE THREAD

**Issue by Qwerty-OFF** [rusefi/hellen154hyundai#71]
Remove D41, D42, D44 [edit: D40, D41, D44], Q7, Q8, Q9 (disable bad LEDs)
Replace R211 with 4.7K (good pull-up)
Replace С221 and C222 with 1n ("high-speed" signal filtration)

https://rusefi.com/docs/ibom/hellen154hyundai-c-ibom.html

**Comment by rusefillc** [comment]
C221
![image](https://user-images.githubusercontent.com/48498823/199602254-07a2e5ca-b54a-43db-a58d-4c79cd5b2669.png)

C222
![image](https://user-images.githubusercontent.com/48498823/199601303-8e113b83-775c-4bd1-803d-fc04b69c8686.png)

**Comment by rusefillc** [comment]
D42? maybe D40 @Qwerty-OFF ?

**Comment by Qwerty-OFF** [comment]
D40, D41, D44

**Comment by rusefillc** [comment]
All rev C boards are good now!
