### ISSUE TITLE
Boards with single smiley face "remote caps"

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#72]
Both boards with single smiley face need capacitor mod

step 1: most of the fix is to remove two capacitors as following

![WhatsApp Image 2022-11-03 at 9 18 31 AM](https://user-images.githubusercontent.com/48498823/199731204-91466a0c-e3bf-40a6-9a47-60cc529f14e1.jpeg)

Later point we will replace 1nF capacitor but there is good hope of progress just that

This is related to #71

**Comment by rusefillc** [comment]
@ElDominio this would need to be done on all boards

**Comment by ElDominio** [comment]
![IMG_20221219_191619.jpg](https://user-images.githubusercontent.com/5685108/208546473-334c22b0-6bde-4d5d-8c90-a826cb129cd3.jpg)

Single smiley with caps removed, still no CKP :(

**Comment by rusefillc** [comment]
I see that https://github.com/rusefi/hellen154hyundai/issues/73 was not applied

![image](https://user-images.githubusercontent.com/48498823/208548488-a0d87ebf-f167-404c-8c2e-8a70f8d6e204.png)

**Comment by ElDominio** [comment]
I see that #73 is called "no smiley face"

**Comment by ElDominio** [comment]
RevC reading incorrectly incorrectly with fix applied.
[DataLogs.zip](https://github.com/rusefi/hellen154hyundai/files/10551828/DataLogs.zip)

![Uploading image.png…]()

Kind of reads, but fails to sync and throws trigger error
