### ISSUE TITLE
Boards without single smiley face

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#73]
step one

remove CRANK transistor and remove CRANK diode

replace CRANK diode with a 0R resistor or a piece of wire

![image](https://user-images.githubusercontent.com/48498823/202325644-26cf6f2d-fd6d-4409-9326-c758129e1270.png)

step two

replace pictured resistor array with 4.7K as provided in one of packages

![image](https://user-images.githubusercontent.com/48498823/202325768-ffa6ea6b-46cc-4c48-ac7d-b98d145de52c.png)

This is related to https://github.com/rusefi/hellen154hyundai/issues/71

**Comment by rusefillc** [comment]
@ElDominio ^^^

**Comment by ElDominio** [comment]
Can I have part number for 4.7k resistor on digikey? I have no idea what I did with the mailed one

**Comment by rusefillc** [comment]
CAY16-4701F4LF
