### ISSUE TITLE
Three boards have returned

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#75]
Have three boards

One looks like order design asking for chip replacement?

What about two boards of newer style?

**Comment by Timbelom** [comment]
https://youtube.com/shorts/m-C_Mx2rcKY?feature=share Board with no markings on it, please clarify status. We we also able to communicate and install latest firmware

**Comment by ElDominio** [comment]
One of them has an ETB trace lifted, the other has a trace lifted at CKP/CMP capacitors
