### ISSUE TITLE
ibom is not happy around U2 & U6

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#79]
![image](https://user-images.githubusercontent.com/48498823/215936776-1a3e036d-cdde-4716-8b6d-85b692e58f18.png)

**Comment by andreika-git** [comment]
U2 is excluded from the BOM via bom_replace.
U6 was the same issue as https://github.com/rusefi/alphax-8chan/issues/35.

**Comment by rusefillc** [comment]
fixed

![image](https://user-images.githubusercontent.com/48498823/221960224-4e019808-b78d-4890-b10b-bbacb1fcb093.png)
