### ISSUE TITLE
Please provide happy rev B tune & log

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#80]
ideally on "20221209_release" but any tune & log of happy vehicle with functional rev B board would work

**Comment by Ankyth** [comment]
[Log 2-1-23 RevC fix.zip](https://github.com/rusefi/hellen154hyundai/files/10562867/Log.2-1-23.RevC.fix.zip)

**Comment by mck1117** [comment]
capture an SD card tooth log too if you can - that is the ground source of truth that the ECU sees.

**Comment by rusefillc** [comment]
Talking to Ray on the phone
Ray says he is looking at 6 boards all with while molex (meaning rev C) in front on him

**Comment by rusefillc** [comment]
Ray says four boards have two small capacitors removed, two boards still have small capacitors.

**Comment by rusefillc** [comment]
@Timbelom three boards should be in NJ soon

* please write unique IDs on these boards Feb1, Feb2, Feb3

* current assumption is that one board has 4.7K array not soldered well, please add solder
* two boards are in different states of not being modified
* remove caps
* remove diode+transistor, install 0R
* replace resistor array

**Comment by rusefillc** [comment]
@Timbelom says five boards have arrived
@Timbelom says two boards do not have #72 fix labeled "f2" and "f3"
@Timbelom says board with most modifications is now labeled "f1"

**Comment by rusefillc** [comment]
![WhatsApp Image 2023-02-12 at 20 30 00](https://user-images.githubusercontent.com/48498823/221425813-e92e38a8-eb0a-4444-8e61-dc2554291797.jpg)

**Comment by Timbelom** [comment]
F4 solder added

**Comment by Timbelom** [comment]
F3 & F2 capacitors removed

**Comment by Timbelom** [comment]
F1, F2 & F3 replaced resistor arrays to 4.7K

**Comment by Timbelom** [comment]
F2 & F3 removed diode+transistor, installed 0R

**Comment by rusefillc** [comment]
F3 & F5 both cam channels  removed diode+transistor, installed 0R

![image](https://user-images.githubusercontent.com/48498823/221632325-791a9a6e-fc44-4a88-a83a-d373852ef617.png)

**Comment by Ankyth** [comment]
F3 and F5 work as intended, both read cam and crank.
F2 reads crank but no CAM

**Comment by rusefillc** [comment]
Hallelujah! Let me modify two more boards to best spec and ship to PR.

**Comment by rusefillc** [comment]
> Hallelujah! Let me modify two more boards to best spec and ship to PR.

https://tools.usps.com/go/TrackConfirmAction?tRef=fullpage&tLc=2&text28777=&tLabels=9405511206214367533690
