### ISSUE TITLE
RevC odd throttle behavior

### ISSUE THREAD

**Issue by ElDominio** [rusefi/hellen154hyundai#83]
revC needs custom PID, ETB bias and sensor calibration. 

for some reason, autocalibrate always fails on revC, but using revB sensor calibration seems to work well enough

[revB and revC tunes.zip](https://github.com/rusefi/hellen154hyundai/files/10749966/revB.and.revC.tunes.zip)

[throttle not calibrating revC.zip](https://github.com/rusefi/hellen154hyundai/files/10750081/throttle.not.calibrating.revC.zip)

**Comment by rusefillc** [comment]
@mck1117 @ElDominio is that new datapoint "revB L9xx5 acts like proteus" vs "rev C with TLE9201 acts like 4chan"?

**Comment by ElDominio** [comment]
Seems like such

**Comment by ElDominio** [comment]
tf is this ew closed
