### ISSUE TITLE
Migrate schematics to megamodule

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#88]
we shall migrate schematics from mcu to [mega-mcu](https://github.com/andreika-git/hellen-one/tree/master/modules/mega-mcu144)

**Comment by Nadezhda-n** [comment]
Вот эта трансформация меня немного настораживает ( в модулях также приходят на разные ножки mcu, мб это изменения именно alphax-2chan?)
![image](https://user-images.githubusercontent.com/99179773/228580158-0ef312e5-262c-42a9-b2a6-cd7004212efe.png)
![image](https://user-images.githubusercontent.com/99179773/228580218-09076fce-4490-47bb-bc66-8223dafac7bb.png)
@rusefillc

**Comment by Nadezhda-n** [comment]
alphax-4 chan у меня не открывается
![image](https://user-images.githubusercontent.com/99179773/228582134-18d774b4-d0d3-4d50-b19e-37a902367d84.png)

**Comment by rusefillc** [comment]
> Вот эта трансформация меня немного настораживает ( в модулях также приходят на разные ножки mcu, мб это изменения именно alphax-2chan?)

пока не понимаю о чём ты. там добавляется ВТОРОЙ CAN, там не двигается первый. Уточни пожалуйста вопрос.

сделал тикет https://github.com/andreika-git/hellen-one/issues/277

**Comment by Nadezhda-n** [comment]
Полагаю, мне также нужно поменять Module-input-0.1 на Module-vr-discrete-0.4 (судя по внутреннему содержимому модулей это так)
![image](https://user-images.githubusercontent.com/99179773/228836290-b5a0733f-1708-4ed7-8bc4-ac3db55a1d2a.png)
![image](https://user-images.githubusercontent.com/99179773/228836224-468784b1-ab62-4ec0-a7d7-64ce6e0ae892.png)
@rusefillc прошу подтверждения, чтобы не было самоуправства и путаницы, мало ли:)

**Comment by rusefillc** [comment]
LOW_EXT1 & LOW_EXT3 нужно перенести на любые свободные пины

Ага, у нас тут видимо для экспериментов две каншины M6 & M13

Висящие P86 P87 намекают, что M6 нужно просто стереть и P86 P87 стереть пока

![image](https://user-images.githubusercontent.com/48498823/228904032-dccd96db-c1b2-4932-a3fa-dee0c2d68931.png)

2chan говорит нам, что вторая CAN шина у нас теперь на SPI2
![image](https://user-images.githubusercontent.com/48498823/228904655-36553711-4e5b-4d68-ae47-d394aed80e24.png)

**Comment by Nadezhda-n** [comment]
> LOW_EXT1 & LOW_EXT3 нужно перенести на любые свободные пины
> 
> Ага, у нас тут видимо для экспериментов две каншины M6 & M13
> 
> 2chan говорит нам, что вторая CAN шина у нас теперь на SPI2. значит эту шину просто переносим аналогично.
> 
> ![image](https://user-images.githubusercontent.com/48498823/228904032-dccd96db-c1b2-4932-a3fa-dee0c2d68931.png)
> 
> ![image](https://user-images.githubusercontent.com/48498823/228904655-36553711-4e5b-4d68-ae47-d394aed80e24.png)
по аналогии на SPI2 занято
![image](https://user-images.githubusercontent.com/99179773/228908447-663f83af-4b37-4bdf-83c3-9a7ce453a4ca.png)
Остались только просто IO

**Comment by Nadezhda-n** [comment]
![image](https://user-images.githubusercontent.com/99179773/229094597-e3838247-6050-4f8f-bd94-1270ffdcab77.png)
Вот этого разъема только нет в мегамодуле, он не нужен?

**Comment by Nadezhda-n** [comment]
Что делать, если не совпадают номиналы подтяжек на плате и внутри мегамодуля?
![image](https://user-images.githubusercontent.com/99179773/229102447-748d73c7-d7c9-4e8c-b522-3d4884216395.png)

**Comment by rusefillc** [comment]
> этого разъема только нет в мегамодуле, он не нужен?

J3 убираем, это рудимент какой-то

**Comment by Nadezhda-n** [comment]
> 
Отлично! Где/как мне это отобразить?
Вот все подтяжки:
![image](https://user-images.githubusercontent.com/99179773/229154065-ac0c349d-8701-4960-8bce-6e57aa2ff9ee.png)

**Comment by Nadezhda-n** [comment]
> > @Nadezhda-n создай плиз отдельный тикет, чтоб вопрос точно не забылся
> 
> @Nadezhda-n создай плиз отдельный тикет, чтоб вопрос точно не забылся

#93 создала, на плате большой тогда это убираю и пока со схематиком тут я все

**Comment by Nadezhda-n** [comment]
А вот еще!
Оставить как было или перенести на соответствующие места?
![Uploading image.png…]()

**Comment by rusefillc** [comment]
@Nadezhda-n вопрос очень хорошие, но лучше менять по минимуму - там прошивке нужно быть совместимой, чем меньше различий в железе - тем проще жить

**Comment by Qwerty-OFF** [comment]
Будем считать что миграция успешна
