### ISSUE TITLE
A/C pressure line pin 54

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#9]
https://github.com/rusefi/rusefi/wiki/Hyundai-Genesis-Coupe#2010

What is it?

Looks like analog signal? really?

![image](https://user-images.githubusercontent.com/48498823/127775591-3e92332a-7d2a-454c-a9c5-f88b4442ee24.png)

**Comment by mck1117** [comment]
it's analog so it can adjust the fan speed to hit pressure target
