### ISSUE TITLE
BOM change: do not populate second CAN transceiver 

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#91]
Just to save the planter and $ we should not populate second CAN transceiver by default

**Comment by rusefillc** [comment]
@Nadezhda-n please add magic line into https://github.com/rusefi/hellen154hyundai/blob/main/bom_replace_hellen154hyundai-d.csv

**Comment by Nadezhda-n** [comment]
I don't fully understand the table and I'm afraid to fill it in wrong :`(

**Comment by Qwerty-OFF** [comment]
Убрал из BOM
