### ISSUE TITLE
replace resistors rev D

### ISSUE THREAD

**Issue by Nadezhda-n** [rusefi/hellen154hyundai#93]
![image](https://user-images.githubusercontent.com/99179773/229158972-869677e3-6b4a-47e3-b5b3-d9a08ec07e89.png)

**Comment by Nadezhda-n** [comment]
![image](https://user-images.githubusercontent.com/99179773/229174242-86d62be9-7cd0-4176-b918-2075409fa51b.png)

**Comment by Qwerty-OFF** [comment]
Заполнил pullups-файл.
