### ISSUE TITLE
Better rev C BOM

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#94]
@Qwerty-OFF please review

https://github.com/rusefi/hellen154hyundai/commit/29ad038e891db121582baa79ad6bc07190f9b42a
https://github.com/rusefi/hellen154hyundai/commit/637b7bab3ceeaac3c054b468e61035faf38fe661
https://github.com/rusefi/hellen154hyundai/commit/db6210c7f83c4a70cdc2b538cc095f5013bda309

**Comment by Qwerty-OFF** [comment]
https://github.com/rusefi/hellen154hyundai/commit/db6210c7f83c4a70cdc2b538cc095f5013bda309 JLC IGBT
https://github.com/rusefi/hellen154hyundai/commit/637b7bab3ceeaac3c054b468e61035faf38fe661 TLS115 HVSON, DNP RZ7899,   DNP AP2331W-7
https://github.com/rusefi/hellen154hyundai/commit/29ad038e891db121582baa79ad6bc07190f9b42a  CRANK, CAM1 capacitor = 1nf, PU = 4.7k, bad CRANK, CAM LEDs disabled

**Comment by Qwerty-OFF** [comment]
https://github.com/rusefi/hellen154hyundai/commit/d68bef4b8e52a273dd27e0ee3cf7f6a5ae4c9ac4 SMCJ30A shortage fix
