### ISSUE TITLE
J2 should be not C27524

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#97]
![image](https://user-images.githubusercontent.com/48498823/232656047-02bbd42c-71d3-4fb6-a9ca-902db4ae8984.png)

![image](https://user-images.githubusercontent.com/48498823/232656182-92ac7aa1-a49a-4d92-ac89-9eda44f550ea.png)

**Comment by rusefillc** [comment]
Looks like last time we've used C239476?

**Comment by Qwerty-OFF** [comment]
В проекте он уже C239476, видимо когда-то раньше поправили. В c-improved изменения внес.
