### ISSUE TITLE
Three hellen154hyundai revC have crank sensor issues

### ISSUE THREAD

**Issue by ElDominio** [rusefi/hellen154hyundai#98]
https://rusefi.com/online/view.php?msq=1451

**Comment by mck1117** [comment]
qualitative notes about how it is?

**Comment by rusefillc** [comment]
@ElDominio @Ankyth in previous episode we had five boards https://github.com/rusefi/hellen154hyundai/issues/80 marked F1, F2, F3, F4 and F5

Are we looking at any of those F boards or else?

https://user-images.githubusercontent.com/48498823/221632325-791a9a6e-fc44-4a88-a83a-d373852ef617.png

**Comment by Ankyth** [comment]
Yes, we have board F7 with this issue. the other 2 boards have all the fixes but werent sent to you

**Comment by ElDominio** [comment]
Edge and Explorer are screwed up on my PC

We have three revC boards with no discernible difference in hardware with CRANK sensor reading issues. Use the same 4 way compound 4.7k resistor, but the crank signal is incredibly screwed up. Any ideas on what to check  (another revC with same firmware and same tune turns on the car just fine)

**Comment by ElDominio** [comment]
what was this? they all seem fine?

**Comment by rusefillc** [comment]
I see something was poorly documented a few months ago :(
