### ISSUE TITLE
+12V_PROT

### ISSUE THREAD

**Issue by Nadezhda-n** [rusefi/hellen154hyundai#99]
![image](https://github.com/rusefi/hellen154hyundai/assets/99179773/181cd2b6-c6d9-4962-a0e5-0c0fe61f91f6)
![image](https://github.com/rusefi/hellen154hyundai/assets/99179773/ef83feb0-27de-4933-839c-897951a120ad)
rev.C / rev. D
Получается, немного разное питание на микросхемах. 
Полагаю, это не критично, но уточнить стоит:)

**Comment by Qwerty-OFF** [comment]
Это про то что мы засунули их в модуль? Все нормально, пусть так будет.

**Comment by Nadezhda-n** [comment]
> Это про то что мы засунули их в модуль? Все нормально, пусть так будет.
Про то, что питание микросхемы было +12V_PROT, стало +12V
